trigger:
  branches:
    include:
      - master

variables:
  GIT_COMMIT: $(Build.SourceVersion)
  BRANCH_NAME: $(Build.SourceBranchName)
  BUILD_URL: "https://dev.azure.com/tronbodya/$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)"

pool:
  vmImage: 'ubuntu-latest'

stages:

- stage: Build
  displayName: 'Build and Run Tests'
  jobs:
  - job: Build
    displayName: 'Build Job'
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '8.0.x'
      displayName: 'Setup .NET'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'restore'
      displayName: 'Restore Dependencies'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        arguments: '--configuration Release'
      displayName: 'Build the Project'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'test'
        projects: 'Consumer.Contract.Tests/Consumer.Contract.Tests.csproj'
        arguments: '--no-build --configuration Release --verbosity normal'
      displayName: 'Run Contract Tests'

- stage: PublishContractTests
  displayName: 'Publish Contract Tests'
  dependsOn: Build
  jobs:
  - job: PublishContractTests
    displayName: 'Publish Contract Tests to PactFlow'
    variables:
      - group: PactFlowSettings
    steps:
    - script: |
        docker run --rm \
          -v $(System.DefaultWorkingDirectory)/Consumer.Contract.Tests/pacts:/pacts \
          pactfoundation/pact-cli:latest \
          publish /pacts \
          --consumer-app-version $(GIT_COMMIT) \
          --branch $(BRANCH_NAME) \
          --build-url $(BUILD_URL) \
          --broker-base-url $(PACT_BROKER_BASE_URL) \
          --broker-token $(PACT_BROKER_TOKEN)
      displayName: 'Publish Contract Tests to PactFlow'

- template: can-i-deploy-template.yml
  parameters:
    pacticipant: 'StudentApiClient'
    environment: 'stage'

- stage: DeployAndRecordDeployment
  displayName: 'Deploy and Record Deployment'
  dependsOn: CanIDeploy
  jobs:
  - job: DeployAndRecord
    displayName: 'Deploy and Record Deployment in PactFlow'
    variables:
      - group: PactFlowSettings
    steps:
    - script: |
        echo "Deploying the application..."
      displayName: 'Deploy Application'

    - script: |
        docker run --rm \
          pactfoundation/pact-cli:latest \
          broker record-deployment \
          --pacticipant StudentApiClient \
          --version $(GIT_COMMIT) \
          --environment stage \
          --broker-base-url $(PACT_BROKER_BASE_URL) \
          --broker-token $(PACT_BROKER_TOKEN)
      displayName: 'Record Deployment in PactFlow'
